# Generated by Django 5.1.6 on 2025-06-21 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('summary_text', models.TextField()),
                ('summary_type', models.CharField(max_length=50)),
                ('highlights', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TextHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('color', models.CharField(max_length=50)),
                ('start_index', models.IntegerField()),
                ('end_index', models.IntegerField()),
                ('summary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_highlights', to='summarizer.documentsummary')),
            ],
        ),
    ]
